### ISSUE TITLE
The permissions class

### ISSUE THREAD

**Issue by FaizanSWE** [JacobSteen777/CSCE-306-CCTV-Project#14]
#include <iostream>
#include <string>

// Permissions class for representing different access privileges
class Permissions {
private:
  bool canEditPersonalInfo;
  bool canViewPersonalInfo;
  bool canAddOrders;
  bool canEditOrders;
  bool canDeleteOrders;
  bool canAddProducts;
  bool canEditProducts;
  bool canDeleteProducts;
  bool canEnterCustomerInfo;

public:
  Permissions(bool canEditPersonalInfo, bool canViewPersonalInfo, bool canAddOrders, bool canEditOrders,
              bool canDeleteOrders, bool canAddProducts, bool canEditProducts, bool canDeleteProducts,
              bool canEnterCustomerInfo)
    : canEditPersonalInfo(canEditPersonalInfo), canViewPersonalInfo(canViewPersonalInfo),
      canAddOrders(canAddOrders), canEditOrders(canEditOrders), canDeleteOrders(canDeleteOrders),
      canAddProducts(canAddProducts), canEditProducts(canEditProducts), canDeleteProducts(canDeleteProducts),
      canEnterCustomerInfo(canEnterCustomerInfo) {}

  bool getCanEditPersonalInfo() { return canEditPersonalInfo; }
  bool getCanViewPersonalInfo() { return canViewPersonalInfo; }
  bool getCanAddOrders() { return canAddOrders; }
  bool getCanEditOrders() { return canEditOrders; }
  bool getCanDeleteOrders() { return canDeleteOrders; }
  bool getCanAddProducts() { return canAddProducts; }
  bool getCanEditProducts() { return canEditProducts; }
  bool getCanDeleteProducts() { return canDeleteProducts; }
  bool getCanEnterCustomerInfo() { return canEnterCustomerInfo; }
};

// CustomerPermissions class for representing the access privileges of customers
class CustomerPermissions : public Permissions {
public:
  CustomerPermissions() : Permissions(true, true, false, false, false, false, false, false, false) {}
};

// SalesPermissions class for representing the access privileges of sales staff
class SalesPermissions : public Permissions {
public:
  SalesPermissions() : Permissions(true, true, true, true, true, false, false, false, false) {}
};

// ManagerPermissions class for representing the access privileges of managers
class ManagerPermissions : public Permissions {
public:
  ManagerPermissions()

**Comment by JacobSteen777** [comment]
This class is far too long and can be simplified significantly. Check the SRS document for the proper format of the class.
