### ISSUE TITLE
Pull req not working so doing an issue for the Product class with subcategories and categories for CAMERAS ONLY 

### ISSUE THREAD

**Issue by FaizanSWE** [JacobSteen777/CSCE-306-CCTV-Project#15]
#include <iostream>
#include <string>
#include <vector>

// Product class for representing different security products
class Product {
private:
  std::string name;
  std::string type;
  double price;

public:
  Product(std::string name, std::string type, double price)
    : name(name), type(type), price(price) {}

  std::string getName() { return name; }
  std::string getType() { return type; }
  double getPrice() { return price; }
};

// Category class for representing different product categories
class Category {
private:
  std::string name;
  std::vector<Product> products;

public:
  Category(std::string name, std::vector<Product> products) : name(name), products(products) {}

  std::string getName() { return name; }
  std::vector<Product> getProducts() { return products; }
};

// Products class for representing the product menu with categories and sub-categories
class Products {
private:
  std::vector<Category> categories;

public:
  Products(std::vector<Category> categories) : categories(categories) {}

  std::vector<Category> getCategories() { return categories; }
};

int main() {
  // Create a vector of products for each sub-category
  std::vector<Product> surveillanceCameras = {
    Product("IP Surveillance Camera", "Surveillance Cameras", 100.0),
    Product("Digital Surveillance Camera", "Surveillance Cameras", 150.0),
    Product("Analog Security Camera", "Surveillance Cameras", 50.0)
  };

  // Create a vector of sub-categories for the cameras category
  std::vector<Category> cameras = {
    Category("Surveillance Cameras", surveillanceCameras)

**Comment by JacobSteen777** [comment]
Class is too specific and does not follow the SRS document class diagram.
