### ISSUE TITLE
orders class

### ISSUE THREAD

**Issue by FaizanSWE** [JacobSteen777/CSCE-306-CCTV-Project#18]
class Orders {
private:
  Product product;
  int amount;

public:
  // Constructor
  Orders(Product product, int amount) : product(product), amount(amount) {}

  // Getters
  Product getProduct() { return product; }
  int getAmount() { return amount; }

  // Setters
  void setAmount(int amount) { this->amount = amount; }
  void setProduct(Product product) { this->product = product; }

  // Other methods
  void removeOrder() { amount = 0; }
};

**Comment by JacobSteen777** [comment]
Looks good and is in accordance to the SRS document. As soon as this is in a PR request it can get merged.
