### ISSUE TITLE
customer class

### ISSUE THREAD

**Issue by FaizanSWE** [JacobSteen777/CSCE-306-CCTV-Project#25]
#include <string>

class Customer {
  private:
    std::string type;

  public:
    // Constructor to initialize the customer type
    Customer(std::string type) {
      this->type = type;
    }

    // Method to get the customer type
    std::string getType() {
      return type;
    }

    // Method to set the customer's phone number
    void setPhone(std::string phone) {
      // Set the customer's phone number
      ...
    }

    // Method to set the customer's address
    void setAddress(std::string address) {
      // Set the customer's address
      ...
    }

    // Method to view the restaurant's menu
    void viewMenu() {
      // Display the menu
      ...
    }

    // Method to get the customer's total sales number
    int getSalesNumber() {
      // Return the customer's total sales number
      ...
    }
};

**Comment by JacobSteen777** [comment]
Doesn't inherit from User class.
